export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as Programming } from './Programming';
export { default as EducationAndExperience } from './EducationAndExperience';
export { default as TestimonialsAndClients } from './TestimonialsAndClients';
export { default as Projects } from './Projects';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
